package org.ufpb.s2dg.entity;

// Generated 13/06/2009 11:07:54 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name = "periodo", schema = "public")
public class Periodo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private PeriodoId id;
	private Set<Turma> turmas = new HashSet<Turma>(0);

	public Periodo() {
	}

	public Periodo(PeriodoId id) {
		this.id = id;
	}

	public Periodo(PeriodoId id, Set<Turma> turmas) {
		this.id = id;
		this.turmas = turmas;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "ano", column = @Column(name = "ano", nullable = false, length = 4)),
			@AttributeOverride(name = "semestre", column = @Column(name = "semestre", nullable = false, length = 1)) })
	@NotNull
	public PeriodoId getId() {
		return this.id;
	}

	public void setId(PeriodoId id) {
		this.id = id;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "periodo")
	public Set<Turma> getTurmas() {
		return this.turmas;
	}

	public void setTurmas(Set<Turma> turmas) {
		this.turmas = turmas;
	}

}
